const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async()=>{ const b=await chromium.launch(); let ok=0,mal=0; const chk=(n,c,x)=>{ if(c){ok++;console.log('✅ '+n);} else {mal++;console.log('❌ '+n+(x?' → '+x:''));} };
 const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
 await ctx.route('**/*', r=>{const u=new URL(r.request().url()); return u.hostname==='localhost'?r.continue():r.abort();});
 const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.goto((process.env.VENTO_BASE||'http://localhost:8765')+'/index.html',{waitUntil:'load'}); await p.waitForTimeout(3500);
 await p.evaluate(async()=>{ try{await enterApp('test',null);}catch(x){} localStorage.setItem('cm-tutorial-seen','1'); document.querySelectorAll('.overlay.show').forEach(o=>o.classList.remove('show'));
   data.products=[{id:'pk',name:'Poker',price:3000,stock:50}]; data.tables[3]={items:[{productId:'pk',name:'Poker',price:3000,qty:10,personId:null,history:[]}],people:[],payments:[]}; saveData(); renderMesas(); openTableModal(3); });
 await p.waitForTimeout(600);
 await p.evaluate(()=>document.getElementById('paymentNote').scrollIntoView({block:'start'}));
 const sel='.pay-card[data-scope=table]';
 chk('Se ve el divisor con el número de personas (÷ 2)', /÷\s*2/.test(await p.textContent(sel+' .pay-div-n')));
 await p.click(sel+' [data-dv="1"]'); await p.waitForTimeout(150);
 let r=await p.evaluate(()=>({n:document.querySelector('.pay-card[data-scope=table] .pay-div-n b').textContent, monto:document.getElementById('paymentAmount').value, info:document.querySelector('.pay-card[data-scope=table] .pay-div-info').textContent, split:document.getElementById('splitCount').value}));
 chk('Con + pasa a 3 personas y pone lo de cada una ($30.000 / 3 = $10.000)', r.n==='3' && r.monto==='10000' && /Entre 3 personas/.test(r.info) && r.split==='3', JSON.stringify(r));
 await p.click(sel+' [data-dv="1"]'); await p.click(sel+' [data-dv="1"]'); await p.waitForTimeout(150);
 r=await p.evaluate(()=>({n:document.querySelector('.pay-card[data-scope=table] .pay-div-n b').textContent, monto:document.getElementById('paymentAmount').value}));
 chk('5 personas → $6.000 cada una', r.n==='5' && r.monto==='6000', JSON.stringify(r));
 await p.click(sel+' [data-dv="-1"]'); await p.waitForTimeout(150);
 r=await p.evaluate(()=>({n:document.querySelector('.pay-card[data-scope=table] .pay-div-n b').textContent, monto:document.getElementById('paymentAmount').value}));
 chk('Con − vuelve a 4 → $7.500', r.n==='4' && r.monto==='7500', JSON.stringify(r));
 await p.screenshot({path:require('os').tmpdir()+'/div1.png'});
 await p.click('#addPaymentBtn'); await p.waitForTimeout(200);
 r=await p.evaluate(()=>({pagos:data.tables[3].payments.map(x=>x.amount), saldo:tableBalance(3)}));
 chk('Registrar: queda el abono de esa persona y el saldo baja', r.pagos[0]===7500 && r.saldo===22500, JSON.stringify(r));
 chk('Sin errores', !errs.length, errs.join('|'));
 console.log('RESULTADO',ok,'bien',mal,'mal'); await b.close(); })();
